[database]
host = 127.0.0.1
port = 5432
database = museum
user = waqar
password = 12345

[email]
enabled = yes
smtp_server = smtp.mail.yahoo.com
smtp_port = 587
sender_email = afridi.waqar@ymail.com
sender_password = password111
#admin_emails = admin1@yourdomain.com,admin2@yourdomain.com
admin_emails = afridi.waqar@gmail.com
use_tls = yes

[alerts]
# Severity levels that trigger email
email_severities = high,critical
# UI notification severities
ui_severities = low,mid,high,critical
# Cooldown period (seconds) between same-type alerts
cooldown_period = 300

[artifacts]
sources =
    https://raw.githubusercontent.com/mthcht/ThreatHunting-Keywords/master/only_keywords.txt,
    https://example.com/your-custom-feed.txt,
    https://another-org.net/iocs.txt
